export const getAddedVersion = (entry: string): string => {
    for (const item of addedVersions) {
        const result = item.entries.find((v) => v[0] === entry)?.[1];
        if (result != null) return result;
    }
    return "";
};

type AddedVersion = {
    category: string;
    entries: [string, string][];
};
const addedVersions: AddedVersion[] = [
    {
        category: "Layout",
        entries: [
            ["aspect-ratio", "v3"],
            ["columns", "v3"],
            ["break-after", "v3"],
            ["break-before", "v3"],
            ["break-inside", "v3"],
            ["box-decoration-break", "v3"],
            ["box-sizing", "v3"],
            ["display", "v3"],
            ["float", "v3"],
            ["clear", "v3"],
            ["isolation", "v3"],
            ["object-fit", "v3"],
            ["object-position", "v3"],
            ["overflow", "v3"],
            ["overscroll-behavior", "v3"],
            ["position", "v3"],
            ["top / right / bottom / left", "v3"],
            ["visibility", "v3"],
            ["z-index", "v3"],
        ],
    },
    {
        category: "Flexbox & Grid",
        entries: [
            ["flex-basis", "v3"],
            ["flex-direction", "v3"],
            ["flex-wrap", "v3"],
            ["flex", "v3"],
            ["flex-grow", "v3"],
            ["flex-shrink", "v3"],
            ["order", "v3"],
            ["grid-template-columns", "v3"],
            ["grid-column", "v3"],
            ["grid-template-rows", "v3"],
            ["grid-row", "v3"],
            ["grid-auto-flow", "v3"],
            ["grid-auto-columns", "v3"],
            ["grid-auto-rows", "v3"],
            ["gap", "v3"],
            ["justify-content", "v3"],
            ["justify-items", "v3"],
            ["justify-self", "v3"],
            ["align-content", "v3"],
            ["align-items", "v3"],
            ["align-self", "v3"],
            ["place-content", "v3"],
            ["place-items", "v3"],
            ["place-self", "v3"],
        ],
    },
    {
        category: "Spacing",
        entries: [
            ["padding", "v3"],
            ["margin", "v3"],
        ],
    },
    {
        category: "Sizing",
        entries: [
            ["width", "v3"],
            ["min-width", "v3"],
            ["max-width", "v3"],
            ["height", "v3"],
            ["min-height", "v3"],
            ["max-height", "v3"],
            ["inline-size", "v4.2"],
            ["min-inline-size", "v4.2"],
            ["max-inline-size", "v4.2"],
            ["block-size", "v4.2"],
            ["min-block-size", "v4.2"],
            ["max-block-size", "v4.2"],
        ],
    },
    {
        category: "Typography",
        entries: [
            ["font-family", "v3"],
            ["font-size", "v3"],
            ["font-smoothing", "v3"],
            ["font-style", "v3"],
            ["font-weight", "v3"],
            ["font-stretch", "v4.0"],
            ["font-variant-numeric", "v3"],
            ["font-feature-settings", "v4.2"],
            ["letter-spacing", "v3"],
            ["line-clamp", "v3"],
            ["line-height", "v3"],
            ["list-style-image", "v3"],
            ["list-style-position", "v3"],
            ["list-style-type", "v3"],
            ["text-align", "v3"],
            ["color", "v3"],
            ["text-decoration-line", "v3"],
            ["text-decoration-color", "v3"],
            ["text-decoration-style", "v3"],
            ["text-decoration-thickness", "v3"],
            ["text-underline-offset", "v3"],
            ["text-transform", "v3"],
            ["text-overflow", "v3"],
            ["text-wrap", "v3"],
            ["text-indent", "v3"],
            ["vertical-align", "v3"],
            ["white-space", "v3"],
            ["word-break", "v3"],
            ["overflow-wrap", "v4.1"],
            ["hyphens", "v3"],
            ["content", "v3"],
        ],
    },
    {
        category: "Backgrounds",
        entries: [
            ["background-attachment", "v3"],
            ["background-clip", "v3"],
            ["background-color", "v3"],
            ["background-image", "v3"],
            ["background-origin", "v3"],
            ["background-position", "v3"],
            ["background-repeat", "v3"],
            ["background-size", "v3"],
        ],
    },
    {
        category: "Borders",
        entries: [
            ["border-radius", "v3"],
            ["border-width", "v3"],
            ["border-color", "v3"],
            ["border-style", "v3"],
            ["outline-width", "v3"],
            ["outline-color", "v3"],
            ["outline-style", "v3"],
            ["outline-offset", "v3"],
        ],
    },
    {
        category: "Effects",
        entries: [
            ["box-shadow", "v3"],
            ["text-shadow", "v4.1"],
            ["opacity", "v3"],
            ["mix-blend-mode", "v3"],
            ["background-blend-mode", "v3"],
            ["mask-clip", "v4.1"],
            ["mask-composite", "v4.1"],
            ["mask-image", "v4.1"],
            ["mask-mode", "v4.1"],
            ["mask-origin", "v4.1"],
            ["mask-position", "v4.1"],
            ["mask-repeat", "v4.1"],
            ["mask-size", "v4.1"],
            ["mask-type", "v4.1"],
        ],
    },
    {
        category: "Filters",
        entries: [
            ["filter", "V4.0"],
            ["filter: blur()", "v3"],
            ["filter: brightness()", "v3"],
            ["filter: contrast()", "v3"],
            ["filter: drop-shadow()", "v3"],
            ["filter: grayscale()", "v3"],
            ["filter: hue-rotate()", "v3"],
            ["filter: invert()", "v3"],
            ["filter: saturate()", "v3"],
            ["filter: sepia()", "v3"],
            ["backdrop-filter", "v4.0"],
            ["backdrop-filter: blur()", "v3"],
            ["backdrop-filter: brightness()", "v3"],
            ["backdrop-filter: contrast()", "v3"],
            ["backdrop-filter: grayscale()", "v3"],
            ["backdrop-filter: hue-rotate()", "v3"],
            ["backdrop-filter: invert()", "v3"],
            ["backdrop-filter: opacity()", "v3"],
            ["backdrop-filter: saturate()", "v3"],
            ["backdrop-filter: sepia()", "v3"],
        ],
    },
    {
        category: "Tables",
        entries: [
            ["border-collapse", "v3"],
            ["border-spacing", "v3"],
            ["table-layout", "v3"],
            ["caption-side", "v3"],
        ],
    },
    {
        category: "Transitions & Animation",
        entries: [
            ["transition-property", "v3"],
            ["transition-behavior", "v4.0"],
            ["transition-duration", "v3"],
            ["transition-timing-function", "v3"],
            ["transition-delay", "v3"],
            ["animation", "v3"],
        ],
    },
    {
        category: "Transforms",
        entries: [
            ["backface-visibility", "v4.0"],
            ["perspective", "v4.0"],
            ["perspective-origin", "v4.0"],
            ["rotate", "v3"],
            ["scale", "v3"],
            ["skew", "v3"],
            ["transform", "v4.0"],
            ["transform-origin", "v3"],
            ["transform-style", "v4.0"],
            ["translate", "v3"],
        ],
    },
    {
        category: "Interactivity",
        entries: [
            ["accent-color", "v3"],
            ["appearance", "v3"],
            ["caret-color", "v3"],
            ["color-scheme", "v4.0"],
            ["cursor", "v3"],
            ["field-sizing", "v4.0"],
            ["pointer-events", "v3"],
            ["resize", "v3"],
            ["scroll-behavior", "v3"],
            ["scroll-margin", "v3"],
            ["scroll-padding", "v3"],
            ["scroll-snap-align", "v3"],
            ["scroll-snap-stop", "v3"],
            ["scroll-snap-type", "v3"],
            ["touch-action", "v3"],
            ["user-select", "v3"],
            ["will-change", "v3"],
        ],
    },
    {
        category: "SVG",
        entries: [
            ["fill", "v3"],
            ["stroke", "v3"],
            ["stroke-width", "v3"],
        ],
    },
    {
        category: "Accessibility",
        entries: [["forced-color-adjust", "v3"]],
    },
];
